spring:
  application:
    name: movie-catalog-service
  webflux:
    base-path: /catalogs/api
  data:
    mongodb:
      database: local

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    appname: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

resilience4j:
  ratelimiter:
    metrics:
      enabled: true
    instances:
      rateLimiterApi:
        register-health-indicator: true